version: "3.8"
services:
  flask:
    image: gokula17/smartmediaserverversion4
    networks:
      - flask-mongo
    ports:
      - "${portNumber}:${portNumber}"
    volumes:
      - "${localDirectory}:/media"
    depends_on:
      - mongodatabase
    environment:
      - portNumber=${portNumber}
  mongodatabase:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - flask-mongo
  
networks:
  flask-mongo:
